### ISSUE TITLE
params file for recorded data is missing

### ISSUE THREAD

**Issue by samcooler** [eulerlab/rave#3]
Hi, I'm working on evaluating and possibly using this code. The params for the simulated data are shown in the notebook, but the params for the real data are unavailable afaik. Could you add those to the repo? Thanks.

-Sam Cooler

**Comment by lhoefling** [comment]
Hi Sam, 
thanks for your interest in RAVE!
I've added the params files and also the checkpoint file for the trained model (incl. state dict) for RAVE. I'll add it later for RAVE+.
Please let me know if you encounter any problems or have any more questions.
Lara
